### ISSUE TITLE
Couldn't find leftImg8bit_transmittanceDBF on Cityspaces Dataset

### ISSUE THREAD

**Issue by sydpan** [fourson/Learning-to-dehaze-with-polarization#3]
Sorry but I couldn't find `leftImg8bit_transmittanceDBF` on [Cityspaces Dataset](https://www.cityscapes-dataset.com/downloads/)

**Comment by fourson** [comment]
It could be migrated. Try this link: https://people.ee.ethz.ch/~csakarid/Model_adaptation_SFSU_dense/
Otherwise it could be in the [leftImg8bit_trainvaltest_foggy.zip](https://www.cityscapes-dataset.com/file-handling/?packageID=29)

**Comment by sydpan** [comment]
> It could be migrated. Try this link: https://people.ee.ethz.ch/~csakarid/Model_adaptation_SFSU_dense/ Otherwise it could be in the [leftImg8bit_trainvaltest_foggy.zip](https://www.cityscapes-dataset.com/file-handling/?packageID=29)

Got it! Thanks a lot for your time and your excellent work!
