### ISSUE TITLE
I used the checkpoint and testdata you provided for the inference, the psnr of "CITYSCAPES_val_QUARTER_munster_000010_000019" alone is only 20, but the composite image in the paper can reach 33, is it because of the pre-training model you provided, not the final model, or do I need a special psnr calculation code?  I use scikit-image library to calculate psnr.

### ISSUE THREAD

**Issue by xdyfazio** [fourson/Learning-to-dehaze-with-polarization#4]

**Comment by fourson** [comment]
Hello there,
Have you run the provided test samples? You can first try to run them to obtain the results to check whether you have correctly run the code.

**Comment by xdyfazio** [comment]
> Hello there, Have you run the provided test samples? You can first try to run them to obtain the results to check whether you have correctly run the code.
I used the checkpoint and test samples you provided, and followed the readme correctly to complete the inference. however, I selected a single de-fogged image and a real clear image to calculate the PSNR, and the results are very different from the results of your paper, is it that the provided checkpoint is not the final model?

**Comment by xdyfazio** [comment]
> Hello there, Have you run the provided test samples? You can first try to run them to obtain the results to check whether you have correctly run the code.

I used the checkpoint and test samples you provided, and followed the readme correctly to complete the inference. however, I selected a single de-fogged image and a real clear image to calculate the PSNR, and the results are very different from the results of your paper, is it that the provided checkpoint is not the final model?

**Comment by xdyfazio** [comment]
I uploaded the code of my inference  in the attachment. The input path is input and the output path is output. PSNRSSIM folder where GT and result are calculated according to a picture I found in the paper respectively. psnr0514.py in scripts is the script I used to calculate the psnr of these two pictures, and resize. py is the script I used to convert the output result into the same size as the original clear picture. I converted the size first before performing psnr calculation


blank
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fourson/Learning-to-dehaze-with-polarization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月15日(星期三) 中午1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fourson/Learning-to-dehaze-with-polarization] I used the checkpoint and testdata you provided for the inference, the psnr of "CITYSCAPES_val_QUARTER_munster_000010_000019" alone is only 20, but the composite image in the paper can reach 33, is it because of the pre-training model you provided, not the final model, or do I need a special psnr calculation code?  I use scikit-image library to calculate psnr. (Issue #4)





 
Hello there,
 Have you run the provided test samples? You can first try to run them to obtain the results to check whether you have correctly run the code.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

Learning-to-dehaze-with-polarization-master.zip (740.96M, 2024年06月14日 13:27 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=06633236f683d1e3d5ca9e831735531d1a170203555059574f5157500218005300071f015302551f56565605010405565702030f311a617e07024058585b061f160c1f52545d0048074e455f455d4c420d0f5344584f00460b0c5c1b5c54124607111c4c5845610f&code=bc2615a2

**Comment by fourson** [comment]
Please follow these instructions to have a try:
1. download the provided checkpoint and data samples in https://drive.google.com/drive/folders/1FwO--21K9GmsS6iGNm44tHMfAoDn6fNs?usp=sharing
2. please run python execute/infer_full.py -r checkpoint/full.pth --data_dir some_test_data/synth/input --result_dir result default
3. then use scripts/visualize_img.py to visualize the result .npy
4. now you have obtained the output data, and you can compute the PSNR

After completing the above instructions, please tell me what are the PSNR and MS-SSIM values you tested on my provided data?

**Comment by xdyfazio** [comment]
Hello, after following your instructions, I have obtained results and the calculated PSNR and SSIM of just one picture (cityscapES_val_quarter_Munster_000010_000019 )are 20.5 and 0.55 respectively. I have attached the output result and the corresponding GT clear picture I found from the leftImg8bit data set. I hope you can help me find out what the problem is, thank you!




blank
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "fourson/Learning-to-dehaze-with-polarization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月15日(星期三) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fourson/Learning-to-dehaze-with-polarization] I used the checkpoint and testdata you provided for the inference, the psnr of "CITYSCAPES_val_QUARTER_munster_000010_000019" alone is only 20, but the composite image in the paper can reach 33, is it because of the pre-training model you provided, not the final model, or do I need a special psnr calculation code?  I use scikit-image library to calculate psnr. (Issue #4)





 
Please follow these instructions to have a try:
  
download the provided checkpoint and data samples in https://drive.google.com/drive/folders/1FwO--21K9GmsS6iGNm44tHMfAoDn6fNs?usp=sharing
 
please run python execute/infer_full.py -r checkpoint/full.pth --data_dir some_test_data/synth/input --result_dir result default
 
then use scripts/visualize_img.py to visualize the result .npy
 
now you have obtained the output data, and you can compute the PSNR
  
After completing the above instructions, please tell me what are the PSNR and MS-SSIM values you tested on my provided data?

**Comment by fourson** [comment]
I think I have found the reason.
The reason why you got the low PSNR is that the ground truth you generated is not "match" the data I uploaded. This is because the random facotrs (\eg, the crop/resize/polarization-related parameters) will be different in different generation process.
The ground truth of my provided input images are uploaded (some_test_data/synth/gt). You can try to re-compute the ground truth. Please tell me the re-computed PSNR values.

**Comment by xdyfazio** [comment]
Wonderful!. With the GT you provided, PSNR is 33.11 and SSIM is 0.944, which is basically consistent with the results of the paper. But I would like to ask how can I get the GT in my own training? In my previous GT image, the original 2048*1024 image was resized from leftImg8bit data set and used as GT. I hope you can answer my question, which is very important for my subsequent training repetition, thank you!

**Comment by fourson** [comment]
Have you followed the instruction in "Preprocess your own data"? I think I have done such jobs already.
If I solve your problem please close the issue and star my project.
